### ISSUE TITLE
sphinx.addnodes.desc missing "domain" and "objtype"

### ISSUE THREAD

**Issue by kartben** [docleaf-labs/docleaf#3]
I think docleaf is not properly setting up the mandatory (https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/sphinx/addnodes.py#L143-L146) `domain` and `objtype` attributes when rendering `sphinx.addnodes.desc` nodes. I am having trouble using the sphinx_immaterial theme for it relies on these to be present
Breathe has code that sets the domain, and the object type to e.g. "xrefsect", "varentry". 

Thanks!

**Comment by michaeljones** [comment]
Thank you for the report. I'll look into adding them now.

**Comment by kartben** [comment]
Awesome, thank you!

**Comment by michaeljones** [comment]
From what I can tell, where docleaf defers to Sphinx directives the `domain` and `objtype` should already be there. There are several places where docleaf creates `desc` nodes directly. 

I have released 0.8.2 to PyPI which attempts to make sure that all directly created `desc` nodes have the right attributes. Are you in a position to try it out and see if it delivers the results you're after? I think it might be I'm not sure if some of the domain generated entries are lacking these attributes for some reason and if docleaf needs to account for that.

**Comment by kartben** [comment]
That's nice, thank you! It's pretty much unblocked me with https://github.com/kartben/zephyr/tree/sphinx-immaterial, although I am still getting errors but that likely does not have to do with doclead, but rather Sphinx Immaterial. In a nutshell, it looks like cross references for variadic functions are causing issues

https://github.com/zephyrproject-rtos/zephyr/blob/fix_doc_dmic_h/include/zephyr/display/mb_display.h#L92-L97

Could it be that the Doxygen doc for these is wrong in the first place? ex. should it be `@param _rows...`?

**Comment by michaeljones** [comment]
I'm glad it helped a little. I'm afraid I'm unsure of exactly what issue you are seeing. Cross references are failing? Ones that are part of the doxygen comments? Or one using the Sphinx domain, eg. :c:define:`MB_IMAGE`? 

Docleaf should be atempting to collect together the params and pass them to the Sphinx macros directive. It renders the text argument for the directive here: https://github.com/docleaf-labs/docleaf/blob/main/rust/src/doxygen/text.rs#L114-L120

I'm seeing the `param` `defname` in the xml so I think it should end up calling `.. c:macro:: MB_IMAGE(_rows...)`.

```xml
      <memberdef kind="define" id="group__mb__display_1ga529a5650acaf699b23b4b4234127cf2c" prot="public" static="no">
        <name>MB_IMAGE</name>
        <param><defname>_rows...</defname></param>
        <initializer>{ .<ref refid="asm-macro-32-bit-gnu_8h_1af16d2973cfd145a2ebdbf9528d5d9ae2" kindref="member">r</ref> = { _rows } }</initializer>
        <briefdescription>
<para>Generate an image object from a given array rows/columns. </para>
        </briefdescription>
        <detaileddescription>
        ...
```

I think Breathe has some logging options to log everything passed to the domains (I think.) I think Docleaf should have the same at some point to help with this. At least allows easier reproduction with pure Sphinx domain directives to see if it works.

**Comment by michaeljones** [comment]
I'm going to close this but feel free to re-open if you have outstanding concerns related to it.

**Comment by kartben** [comment]
> I'm going to close this but feel free to re-open if you have outstanding concerns related to it.

Yes, thanks! I'll investigate more as I think the issue might rather be with the theme I'm using.
